import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <ClerkProvider>
      <html lang="en">
        <body style={{'width':'100vw', 'dispaly':'flex','justify-content':'center'}}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
